import { StyleProp, TextStyle } from 'react-native'

export const visually-hidden: StyleProp<TextStyle>
export const container: StyleProp<TextStyle>
export const head: StyleProp<TextStyle>
export const head__link: StyleProp<TextStyle>
export const head__img: StyleProp<TextStyle>
export const nav: StyleProp<TextStyle>
export const nav__list: StyleProp<TextStyle>
export const nav__item:nth-child(2): StyleProp<TextStyle>
export const nav__link: StyleProp<TextStyle>
export const hero: StyleProp<TextStyle>
export const hero__img: StyleProp<TextStyle>
export const hero__content: StyleProp<TextStyle>
export const hero__title: StyleProp<TextStyle>
export const hero__text: StyleProp<TextStyle>
export const task: StyleProp<TextStyle>
export const task__img: StyleProp<TextStyle>
export const task__content: StyleProp<TextStyle>
export const task__title: StyleProp<TextStyle>
export const task__text: StyleProp<TextStyle>
export const quality: StyleProp<TextStyle>
export const quality__content: StyleProp<TextStyle>
export const quality__title: StyleProp<TextStyle>
export const quality__text: StyleProp<TextStyle>
export const quality__img: StyleProp<TextStyle>
export const address: StyleProp<TextStyle>
export const address__title: StyleProp<TextStyle>
export const address__list: StyleProp<TextStyle>
export const address__item: StyleProp<TextStyle>
export const address__item:nth-child(2): StyleProp<TextStyle>
export const adderss__img--unitedKingdom,adderss__img--canada,adderss__img--australia: StyleProp<TextStyle>
export const adderss__img--unitedKingdom: StyleProp<TextStyle>
export const adderss__img--canada: StyleProp<TextStyle>
export const adderss__img--australia: StyleProp<TextStyle>
export const address__item--title: StyleProp<TextStyle>
export const location: StyleProp<TextStyle>
export const location__item: StyleProp<TextStyle>
export const footer: StyleProp<TextStyle>
export const footer__img: StyleProp<TextStyle>
export const footer__list: StyleProp<TextStyle>
export const footer__item:nth-child(2): StyleProp<TextStyle>
export const network: StyleProp<TextStyle>
export const network__item:nth-child(2): StyleProp<TextStyle>
export const footer__link: StyleProp<TextStyle>
export const network__img: StyleProp<TextStyle>
export const network__img--tiwitter: StyleProp<TextStyle>
